# Generated by Django 4.1.7 on 2023-02-15 22:02

from django.db import migrations, models

import dayrizer_task.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FizzBuzz",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.PositiveIntegerField(unique=True)),
                (
                    "fizzbuzz",
                    models.CharField(
                        choices=[
                            (dayrizer_task.models.FizzBuzzStatus["Null"], "Null"),
                            (dayrizer_task.models.FizzBuzzStatus["Fizz"], "Fizz"),
                            (dayrizer_task.models.FizzBuzzStatus["Buzz"], "Buzz"),
                            (
                                dayrizer_task.models.FizzBuzzStatus["Fizzbuzz"],
                                "FizzBuzz",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                ("placeholder_post", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
